services:
  - type: web
      name: tdrive-automacao
          runtime: node
              startCommand: npm start
                  buildCommand: apt-get update && apt-get install -y chromium-browser chromium-codecs-ffmpeg && npm ci
                      plan: free
                          envVars:
                                - key: PUPPETEER_SKIP_DOWNLOAD
                                        value: "true"
                                              - key: PUPPETEER_EXECUTABLE_PATH
                                                      value: "/usr/bin/chromium-browser"
