// TDrive Pro v5.3 - RASCUNHO COM MELHORIAS PUPPETEER// Versão beta com timeouts aumentados e melhor tratamento de erros// Deploy em https://paginaexemplo.onrender.comconst express = require('express');
const puppeteer = require('puppeteer');
const crypto = require('crypto');
const app = express();
const PORT = process.env.PORT || 3000;

app.use(express.json());
const fichas = {};

// ====== API: SUBMIT FICHA AO FANDI ======
app.post('/api/submit-fandi', async (req, res) => {
  try {
      const dados = req.body;
          if (!dados.cpf || !dados.name) {
                return res.json({ success: false, message: 'CPF ou Nome faltando' });
                    }

                        const fandi_id = 'PROP-' + Date.now() + '-' + crypto.randomBytes(6).toString('hex');
                            fichas[fandi_id] = { ...dados, fandi_id, criadoEm: new Date(), status: 'enviada' };

                                console.log('[SUBMIT] Nova ficha:', fandi_id);

                                    // Automação Puppeteer melhorada    let browser;    try {
                                          browser = await puppeteer.launch({
                                                  headless: 'new',
                                                          args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage', '--disable-gpu'],
                                                                  timeout: 60000
                                                                        });

                                                                              const page = await browser.newPage();
                                                                                    page.setDefaultNavigationTimeout(60000);
                                                                                          page.setDefaultTimeout(60000);

                                                                                                console.log('[PUPPETEER] Acessando Fandi...');
                                                                                                      await page.goto('https://jsl.fandi.com.br/operacao/novo', { waitUntil: 'networkidle2', timeout: 60000 });
                                                                                                      
                                                                                                            // Aguardar campo CPF      await page.waitForSelector('input[name="cpf"]', { timeout: 30000 }).catch(e => {
                                                                                                                    throw new Error('Campo CPF não encontrado');
                                                                                                                          });
                                                                                                                          
                                                                                                                                // Preencher campos com delays      await page.type('input[name="cpf"]', dados.cpf, { delay: 80 });
                                                                                                                                      await page.waitForTimeout(300);
                                                                                                                                            await page.type('input[name="name"]', dados.name, { delay: 80 });
                                                                                                                                                  await page.waitForTimeout(300);
                                                                                                                                                        await page.type('input[name="mother_name"]', dados.mother || '', { delay: 80 });
                                                                                                                                                              await page.waitForTimeout(300);
                                                                                                                                                                    await page.type('input[name="phone"]', dados.phone || '', { delay: 80 });
                                                                                                                                                                          await page.waitForTimeout(300);
                                                                                                                                                                                await page.type('input[name="salary"]', dados.salary || '', { delay: 80 });
                                                                                                                                                                                      await page.waitForTimeout(300);
                                                                                                                                                                                            await page.type('input[name="cep"]', dados.cep || '', { delay: 80 });
                                                                                                                                                                                                  await page.waitForTimeout(300);
                                                                                                                                                                                                        await page.type('input[name="address"]', dados.address || '', { delay: 80 });
                                                                                                                                                                                                              await page.waitForTimeout(300);
                                                                                                                                                                                                                    await page.type('input[name="neighborhood"]', dados.neighborhood || '', { delay: 80 });
                                                                                                                                                                                                                          await page.waitForTimeout(500);
                                                                                                                                                                                                                          
                                                                                                                                                                                                                                // Detectar e clicar submit
                                                                                                                                                                                                                                      const submitBtn = await page.$('button[type="submit"]');
                                                                                                                                                                                                                                            if (!submitBtn) throw new Error('Botão submit não encontrado');
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                  console.log('[PUPPETEER] Enviando ficha...');
                                                                                                                                                                                                                                                        await Promise.all([
                                                                                                                                                                                                                                                                submitBtn.click(),
                                                                                                                                                                                                                                                                        page.waitForNavigation({ waitUntil: 'networkidle2', timeout: 45000 }).catch(() => {})
                                                                                                                                                                                                                                                                              ]);
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                    fichas[fandi_id].status = 'processada';
                                                                                                                                                                                                                                                                                          console.log('[PUPPETEER] ✅ Enviado!');
                                                                                                                                                                                                                                                                                                await browser.close();
                                                                                                                                                                                                                                                                                                    } catch (puppeteerError) {
                                                                                                                                                                                                                                                                                                          console.error('[PUPPETEER ERROR]', puppeteerError.message);
                                                                                                                                                                                                                                                                                                                fichas[fandi_id].status = 'erro';
                                                                                                                                                                                                                                                                                                                      fichas[fandi_id].erro = puppeteerError.message;
                                                                                                                                                                                                                                                                                                                            if (browser) await browser.close();
                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                    res.json({ success: true, fandi_id, dados: fichas[fandi_id] });
                                                                                                                                                                                                                                                                                                                                      } catch (error) {
                                                                                                                                                                                                                                                                                                                                          console.error('[ERROR]', error.message);
                                                                                                                                                                                                                                                                                                                                              res.json({ success: false, message: error.message });
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                app.get('/api/fichas', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                  const lista = Object.values(fichas).sort((a, b) => new Date(b.criadoEm) - new Date(a.criadoEm));
                                                                                                                                                                                                                                                                                                                                                    res.json({ success: true, total: lista.length, fichas: lista });
                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                    app.get('/api/status/:fandi_id', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                      const ficha = fichas[req.params.fandi_id];
                                                                                                                                                                                                                                                                                                                                                        if (!ficha) return res.status(404).json({ success: false, message: 'Não encontrada' });
                                                                                                                                                                                                                                                                                                                                                          res.json({ success: true, ficha });
                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                          app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                            console.log('🚀 TDrive Pro v5.3 na porta ' + PORT);
                                                                                                                                                                                                                                                                                                                                                            });
